blank_issues_enabled: false
contact_links:
  - name: "ğŸ’• Please support my work on Forge and other Emacs projects"
    url: https://github.com/sponsors/tarsius
    about: Thanks! Any support helps. These donations from users are my only income.
  - name: "ğŸ’¡ Suggest a feature â˜› please open a discussion instead of an issue"
    url: https://github.com/magit/forge/discussions/categories/ideas
    about: Start a discussion suggesting an improvement or a new feature.
  - name: "ğŸ†˜ Ask the community for support"
    url: https://www.reddit.com/r/emacs
    about: Please also consider supporting others.
  - name: "ğŸ†˜ Ask the maintainers for support â˜› please open a discussion"
    url: https://github.com/magit/forge/discussions/categories/q-a
    about: Please keep in mind that our bandwidth is limited.
  - name: "â„¹ï¸ Forge FAQ"
    url: https://magit.vc/manual/forge/FAQ.html
    about: Others might have had the same question before.
  - name: "â„¹ï¸ Forge Manual"
    url: https://magit.vc/manual/forge/#Top
    about: The fine manual may also be of use.
